title: EZPage Dev
author:
  name: rsnyder
  email: ron@snyderjr.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >-
  Quickly build websites using Github Pages, Markdown, and interactive viewers.

github:
  owner: rsnyder
  repo: ezpage-dev
  branch: main

url: https://rsnyder.github.io/ezpage-dev/
baseurl: /ezpage-dev

# components: https://rsnyder.github.io/ezpage-wc/js/index.js,https://juncture-digital.github.io/web-components/js/index.js
components: http://localhost:5173/src/main.ts,https://juncture-digital.github.io/web-components/js/index.js
