title: Kent Digital Map
tagline: 
banner: /images/Bleak_house_postcard.jpg
favicon: /images/favicon.ico
customCSS: /css/custom.css

# When using a custom domain these fields must be updated to match
# the account and repository name
acct: kent-map
repo: kent

ref: v1.1.0

######################################################
# Defines options shown in the header navigation menu
######################################################
nav:
- label: About
  icon: info
  path: /about
- label: Contact Us
  icon: envelope
  path: "/contact-us"

# If the /contact-us path is defined for the nav menu a contact form will be enabled
# The following information is used in the display and processing of the contact form.
contactForm:
  toEmail:
  - ron.snyder@ithaka.org
  - carolyn.oulton@canterbury.ac.uk
  subject: Kent Digital Map Contact

#######################################################
# Base URL of server used for serving and optionally
# creating IIIF presentation manifests
######################################################
iiifServer: https://iiif.juncture-digital.org

siteAdmins:
- rsnyder
- DigiHum1

######################################################
# Optional credentials used for GitHub API and OAuth integration
######################################################

# GitHub upscoped API token used for content retrivals
#ghUnscopedToken: <Base64 encoded GitHub unscoped token>

# Google Cloud OAuth settings for GithHub login via Juncture
#gcAuthDomain: <Base64-encoded Google Cloud OAuth domain>
#gcApiKey: <Base64-encoded restricted access Google Cloud API key>
